create extension if not exists pgcrypto;

create table if not exists public.settings (
  id uuid primary key default gen_random_uuid(),
  key text not null unique,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.guests (
  id bigint generated by default as identity primary key,
  primer_nombre text,
  segundo_nombre text,
  primer_apellido text,
  segundo_apellido text,
  de_parte text,
  tipo_invitacion text,
  id_relacionado text,
  confirmacion text not null default 'Pendiente' check (confirmacion in ('Sí', 'No', 'Pendiente')),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  cancion text not null,
  artista text,
  sugerido_por text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  nombre text not null,
  mensaje text not null,
  visible boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_guests_id_relacionado on public.guests (id_relacionado);
create index if not exists idx_guests_confirmacion on public.guests (confirmacion);
create index if not exists idx_settings_key on public.settings (key);
create index if not exists idx_songs_created_at on public.songs (created_at desc);
create index if not exists idx_messages_created_at on public.messages (created_at desc);

create or replace function public.touch_updated_at()
returns trigger as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_guests_updated_at on public.guests;
create trigger trg_guests_updated_at
before update on public.guests
for each row
execute function public.touch_updated_at();

create or replace function public.touch_settings_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_settings_updated_at on public.settings;
create trigger trg_settings_updated_at
before update on public.settings
for each row
execute function public.touch_settings_updated_at();

alter table public.guests enable row level security;
alter table public.messages enable row level security;
alter table public.songs enable row level security;
alter table public.settings enable row level security;

drop policy if exists "Allow public read on guest data" on public.guests;
create policy "Allow public read on guest data"
on public.guests
for select
using (true);

drop policy if exists "Allow public read on settings" on public.settings;
create policy "Allow public read on settings"
on public.settings
for select
using (true);

drop policy if exists "Allow public read on songs" on public.songs;
create policy "Allow public read on songs"
on public.songs
for select
using (true);

drop policy if exists "Allow public read on messages" on public.messages;
create policy "Allow public read on messages"
on public.messages
for select
using (true);

drop policy if exists "Allow app write on settings" on public.settings;
create policy "Allow app write on settings"
on public.settings
for insert
with check (true);

drop policy if exists "Allow app update on settings" on public.settings;
create policy "Allow app update on settings"
on public.settings
for update
using (true)
with check (true);

drop policy if exists "Allow app write on guests" on public.guests;
create policy "Allow app write on guests"
on public.guests
for insert
with check (true);

drop policy if exists "Allow app update on guests" on public.guests;
create policy "Allow app update on guests"
on public.guests
for update
using (true)
with check (true);

drop policy if exists "Allow app write on songs" on public.songs;
create policy "Allow app write on songs"
on public.songs
for insert
with check (true);

drop policy if exists "Allow app update on songs" on public.songs;
create policy "Allow app update on songs"
on public.songs
for update
using (true)
with check (true);

drop policy if exists "Allow app write on messages" on public.messages;
create policy "Allow app write on messages"
on public.messages
for insert
with check (true);

drop policy if exists "Allow app update on messages" on public.messages;
create policy "Allow app update on messages"
on public.messages
for update
using (true)
with check (true);
